version: '3.4'

services:
  efisherybackendtest:
    image: efisherybackendtest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3079:3079
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
